### DISCUSSION TITLE
Prohibited transition on crossing

### DISCUSSION THREAD

**Discussion by Azbesciak** [OvertureMaps/data#294] [Discussion]
Hi, first of all I think [turn restrictions section](https://docs.overturemaps.org/schema/attributes/transportation/roads/#turn-restrictions) needs to be improved; there is still old schema (road based property), also 'via' example is invalid (segments order, via segment `via-turn-restriction-via` is rather `overture:transportation:example:simple-road2`).

Also in general the data is quite poor - for the whole Berlin I have found only 16 simple prohibited turns.

To the point - assuming we have a crossing like below:
![image](https://github.com/OvertureMaps/schema/assets/17334466/2a2177c3-a2f2-409d-84d8-a43cff467d1b)

how to model prevention of the transition marked with the arrow?
From the schema description, I would assume Segment B would have prohibited transition to Segment A on connector 2.
All would be fine but then is it left turn or right turn?
So maybe a list of connectors there would be better?

**Comment by sanjibdutta1** [comment]
Assuming that the geometry orientation of the segments are forward i.e segment A (Connector1, Connector2, Connector3) and segment B (Connector5, Connector2, Connector4), the restriction would be modeled as a property on segment B like:

```
id: segment B
road:
  restrictions:
    prohibited_transitions:
      - sequence:
        - segment_id: segment A
          connector_id: Connector 2
        final_heading: forward
    when:
      heading: forward
```

      

When heading:forward will indicate south -> north travel on segment A and final_heading: forward means west->east travel on segment A and the restriction is on connector 2, so there is not ambiguity.
