### DISCUSSION TITLE
Vehicle types description

### DISCUSSION THREAD

**Discussion by Azbesciak** [OvertureMaps/data#301] [Discussion]
Hi,
there are the following types of vehicle types for the transportation layer:
```yml
      enum: [ vehicle, motor_vehicle, car, truck, motorcycle, foot, bicycle, bus, hgv, hov, emergency ]
      "$comment": >-
        motor_vehicle includes car, truck and motorcycle
```
first of all, what is the difference between `truck` and `hgv`?
secondly, is it correct that `motor_vehicle` does not contain `bus`?
