### DISCUSSION TITLE
Single Schema object?

### DISCUSSION THREAD

**Discussion by arthurgailes** [OvertureMaps/data#312] [Discussion]
Hello, 

Does anyone know where I might find a unified schema object/dictionary for the download paths, rather than the by-theme dicts available online? Or know how to easily build one?

Thanks in advance!

**Comment by jwass** [comment]
Hi @arthurgailes - can you elaborate more on what you're looking for?

**Reply by arthurgailes** [reply]
Apologies for not being clearer. We currently have schema as in [Places](https://docs.overturemaps.org/schema/reference/places/place), as below 

```
"$schema": https://json-schema.org/draft/2020-12/schema
title: place
description: >-
  A Place is a point representation of a real-world facility, service,
  or amenity. Place features are compatible with GeoJSON Point features.
type: object
properties:
  id:
    "$ref": ../defs.yaml#/$defs/propertyDefinitions/id
  geometry:
    description: >-
      Place's geometry which MUST be a Point as defined by GeoJSON
      schema.
    unevaluatedProperties: false
    oneOf:
      - "$ref": https://geojson.org/schema/Point.json
  properties:
    unevaluatedProperties: false
    required: [categories]
    allOf:
      - "$ref": ../defs.yaml#/$defs/propertyContainers/overtureFeaturePropertiesContainer
      - "$ref": ../defs.yaml#/$defs/propertyContainers/namesContainer
    properties:
      categories:
        description: The categories of the place. The list of categories can be found <TODO>.
        type: object
        required: [main]
        properties:
          main:
            description: The main category of the place.
            type: string
          alternate:
            description: Alternate categories of the place. Some places might fit into two categories, e.g. a book store and a coffee shop. In such a case, the main category can be augmented with additional applicable categories.
            type: array
            items:
              type: string
            uniqueItems: true
      confidence:
        description: The confidence of the existence of the place. It's a number between 0 and 1. 0 means that we're sure that the place doesn't exist (anymore). 1 means that we're sure that the place exists. If there's no value for the confidence, it means that we don't have any confidence information.
        type: number
        minimum: 0
        maximum: 1
...
```

What I'm looking for is a single object/dictionary of all of these schemas denoted by theme/type, i.e.

```
{
  places: {
    type: {
      place : {
       names : {
...
```

Primarily so I have a data types dictionary in advance.
